name: Deploy to EB
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Generate deployment package (only hero-ai)
        run: |
            cd hero-ai
            zip -r ../deploy.zip . -x "*.git*"

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Hero-hrsystem-python  # EB 애플리케이션 이름
          environment_name: Hero-hrsystem-python-env  # EB 환경 이름
          version_label: ${{ github.sha }}
          region: ap-northeast-2
          deployment_package: deploy.zip
          use_existing_version_if_available: true